const notificationType={
APPOINTMENT_CREATED:'APPOINTMENT_CREATED',
APPOINTMENT_CANCELLED:'APPOINTMENT_CANCELLED',
APPOINTMENT_REMINDER:'APPOINTMENT_REMINDER',
CHAT_MESSAGE:'CHAT_MESSAGE',
};
module.exports=notificationType;